### ISSUE TITLE
Cant import weppy

### ISSUE THREAD

**Issue by angus-galbraith** [emmett-framework/emmett#300]
Have installed weppy in windows 10, when I go to import i get the following error.
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Angus Galbraith\AppData\Local\Programs\Python\Python39\lib\site-packages\weppy\__init__.py", line 3, in <module>
    from .app import App, AppModule
  File "C:\Users\Angus Galbraith\AppData\Local\Programs\Python\Python39\lib\site-packages\weppy\app.py", line 21, in <module>
    from .expose import Expose, url
  File "C:\Users\Angus Galbraith\AppData\Local\Programs\Python\Python39\lib\site-packages\weppy\expose.py", line 19, in <module>
    from .pipeline import Pipeline, Pipe
  File "C:\Users\Angus Galbraith\AppData\Local\Programs\Python\Python39\lib\site-packages\weppy\pipeline.py", line 14, in <module>
    from .http import HTTP, redirect
  File "C:\Users\Angus Galbraith\AppData\Local\Programs\Python\Python39\lib\site-packages\weppy\http.py", line 13, in <module>
    from .globals import current
  File "C:\Users\Angus Galbraith\AppData\Local\Programs\Python\Python39\lib\site-packages\weppy\globals.py", line 26, in <module>
    from .html import htmlescape
  File "C:\Users\Angus Galbraith\AppData\Local\Programs\Python\Python39\lib\site-packages\weppy\html.py", line 18, in <module>
    from .libs.sanitizer import sanitize
  File "C:\Users\Angus Galbraith\AppData\Local\Programs\Python\Python39\lib\site-packages\weppy\libs\sanitizer.py", line 22, in <module>
    from cgi import escape
ImportError: cannot import name 'escape' from 'cgi' (C:\Users\Angus Galbraith\AppData\Local\Programs\Python\Python39\lib\cgi.py)`

Any suugestions would be greatly appreciated.

**Comment by gi0baro** [comment]
@angus-galbraith I'm sorry but weppy is not compatible with Python 3.9.
You should use Python 3.7 or switch to Emmett.

**Comment by angus-galbraith** [comment]
Hi Thanks for the quick reply, have installed Emmett.
Working well

Thanks

Angus
